# Remember to run `poetry update` after you edit this file!

[tool.poetry]
    name = "wikipack"
    description = "A Wiki for Royalnet"
    version = "1.1.0"
    authors = ["Stefano Pigozzi <ste.pigozzi@gmail.com>"]
    license = "AGPL-3.0+"
    homepage = "https://github.com/Steffo99/wikipack/"
    classifiers = [
        "Development Status :: 3 - Alpha",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)"
    ]
    readme = "README.md"

# Library dependencies
[tool.poetry.dependencies]
    python = "^3.8"

    [tool.poetry.dependencies.royalnet]
        version = "~5.9.0"
        extras = [
            "alchemy_easy",
            "constellation",
        ]

# Development dependencies
[tool.poetry.dev-dependencies]



# Optional dependencies
[tool.poetry.extras]


# Poetry stuff
# Leave it alone!
[build-system]
    requires = ["poetry>=0.12"]
    build-backend = "poetry.masonry.api"
