[tool.poetry]
name = "jiradata"
version = "1.1.0"
description = "Simple JIRA data manipulation"
authors = ["Khalid <khalidck@gmail.com>"]

[tool.poetry.scripts]
jiradata = 'jiradata.jiradata:cli'

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5"
pylint = "^2.4.4"
isort = "^4.3.21"
mypy = "^0.770"
pytest-datadir = "^1.3.1"
tox = "^3.15.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
