[tool.poetry]
name = "grove_keeper"
version = "0.1.0"
description = "A simple password manager to be used with Good Bot."
authors = ["tricky <etienne.parent@beon.ca>"]
license = "MIT"
readme = "README.rst"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: POSIX"
]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
cryptography = "^2.9.2"

[tool.poetry.dev-dependencies]
pytest = "^4.6"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
groveKeeper = "grove_keeper.cli:main"
