# https://hackersandslackers.com/python-poetry-package-manager/
[tool.poetry]
name = "wws"
version = "0.1.10"
description = "A simple utility to synchronize local and remote paths"
authors = ["Daniel Porto <daniel.porto@gmail.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
plumbum = "^1.6"
funcy = "^1.14"
pyyaml = "^5.3"
pprint = "^0.1"
tabulate = "^0.8.7"
printy = "^2.0.1"
emoji = "^0.5.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

# this block defines how the executable is called.
# https://python-poetry.org/docs/pyproject/
# <cli alias> = "<python module(dir)>.<python module (script name)>:<script resource>"
[tool.poetry.scripts]
wws = "wws.wws:main"

[build-system]
requires = ["poetry>=1.0.9"]
build-backend = "poetry.masonry.api"

