[tool.poetry]
name = "pgdiff"
version = "0.1.14"
description = ""
authors = ["Your Name <you@example.com>"]
include = ["sql/*.sql", "pgdiff/py.typed"]
packages = [
    { include = "pgdiff" },
]

[tool.poetry.dependencies]
python = "^3.6"
psycopg2-binary = "^2.8.5"
typing_extensions = "^3.7.4"
click = "^7.1.2"
mypy = "^0.770"
networkx = "^2.4"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"

[tool.poetry.scripts]
pgdiff = "pgdiff.cli:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
