[tool.poetry]
name = "lecture_transcriber"
version = "0.3.0"
description = "A DeepSpeech-based transcriber using DeepSegment to separate sentences in a long audio recording."
authors = ["Harrison Morgan <harrison.morgan@gmail.com>"]
license = "bsd-3-clause"

[tool.poetry.dependencies]
python = "^3.7"
deepspeech = "0.6.1"
deepsegment = "2.3.0"
pydub = "0.23.1"
sox = "1.3.7"
tqdm = "4.43.0"
tensorflow = "^2.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
